[versions]
druid = "1.2.20"
h2 = "1.4.200"
logback = "1.2.12"
[libraries]
druid = { module = "com.alibaba:druid", version.ref = "druid" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }